services:
  postgres:
    image: postgres:alpine
    environment:
      POSTGRES_DB: postgres
      POSTGRES_USER: postgres  # Add this line
      POSTGRES_PASSWORD: password
    network_mode: host
    volumes:
      - postgres:/var/lib/postgresql/data

volumes:
  postgres:
